#include "STD_TYPES.h"
#include "MACROS.h"

#include "MDIO_interface.h"

#include "HSTEPPER_config.h"
#include "HSTEPPER_interface.h"
#include "HSTEPPER_private.h"
#include <util/delay.h>



void HStepperPlay_CCW(u16 deg)
{
	deg *= 10;
	deg /= 7 ;

	for (u32 i=0 ; i < deg ; i++)
	{
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT, STPPER_BLUE_PIN 	, DIO_PIN_HIGH);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT, STPPER_PINK_PIN 	, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT, STPPER_YELLOW_PIN, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT, STPPER_ORANGE_PIN, DIO_PIN_LOW);
		_delay_ms(2);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT, STPPER_BLUE_PIN 	, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT, STPPER_PINK_PIN 	, DIO_PIN_HIGH);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT, STPPER_YELLOW_PIN, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT, STPPER_ORANGE_PIN, DIO_PIN_LOW);
		_delay_ms(2);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT, STPPER_BLUE_PIN 	, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT, STPPER_PINK_PIN 	, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT, STPPER_YELLOW_PIN, DIO_PIN_HIGH);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT, STPPER_ORANGE_PIN, DIO_PIN_LOW);
		_delay_ms(2);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT, STPPER_BLUE_PIN 	, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT, STPPER_PINK_PIN 	, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT, STPPER_YELLOW_PIN, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT, STPPER_ORANGE_PIN, DIO_PIN_HIGH);
		_delay_ms(2);
	}
}
void HStepperPlay_CW(u16 deg)
{

	deg *= 10;
	deg /= 7 ;

	for (u32 i=0 ; i < deg ; i++)
	{
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT,STPPER_ORANGE_PIN,DIO_PIN_HIGH);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT,STPPER_YELLOW_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT,STPPER_PINK_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT,STPPER_BLUE_PIN,DIO_PIN_LOW);
		_delay_ms(2);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT,STPPER_ORANGE_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT,STPPER_YELLOW_PIN,DIO_PIN_HIGH);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT,STPPER_PINK_PIN, DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT,STPPER_BLUE_PIN, DIO_PIN_LOW);
		_delay_ms(2);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT,STPPER_ORANGE_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT,STPPER_YELLOW_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT,STPPER_PINK_PIN,DIO_PIN_HIGH);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT,STPPER_BLUE_PIN,DIO_PIN_LOW);
		_delay_ms(2);
		MDIO_VoidSetPinValue(STPPER_ORANGE_PORT,STPPER_ORANGE_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_YELLOW_PORT,STPPER_PINK_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_PINK_PORT,STPPER_PINK_PIN,DIO_PIN_LOW);
		MDIO_VoidSetPinValue(STPPER_BLUE_PORT,STPPER_BLUE_PIN,DIO_PIN_HIGH);
		_delay_ms(2);
	}
}


